//! Which of two behaviours to follow where the original has a defect.
//!
//! The port corrects four statistics defects, a memory formula and a perf counter that charts as a zero, all of them listed in `divergences.md`.
//! Corrected is the default, because publishing numbers we know to be wrong in order to match somebody else's numbers is not reproduction, it is imitation.
//!
//! Upstream mode reproduces every defect exactly. That is not a courtesy setting. It is how the original's published results can be regenerated byte for byte, which is the only evidence that the corrections are corrections rather than differences.

use std::fmt;
use std::str::FromStr;

/// Corrected behaviour, or the original's behaviour including its defects.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Compat {
    /// What this harness does by default.
    #[default]
    Corrected,
    /// What the original does, defects included.
    Upstream,
}

impl Compat {
    /// Whether to reproduce the original's defects.
    #[must_use]
    pub const fn is_upstream(self) -> bool {
        matches!(self, Self::Upstream)
    }

    /// The name used on the command line and in the run file.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Corrected => "corrected",
            Self::Upstream => "upstream",
        }
    }
}

impl fmt::Display for Compat {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

/// A `--compat` value that is neither of the two.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BadCompat(pub String);

impl fmt::Display for BadCompat {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "unknown compat mode {:?}, expected corrected or upstream",
            self.0
        )
    }
}

impl std::error::Error for BadCompat {}

impl FromStr for Compat {
    type Err = BadCompat;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "corrected" => Ok(Self::Corrected),
            "upstream" => Ok(Self::Upstream),
            other => Err(BadCompat(other.to_owned())),
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::Compat;

    #[test]
    fn correct_by_default() {
        assert_eq!(Compat::default(), Compat::Corrected);
        assert!(!Compat::default().is_upstream());
    }

    #[test]
    fn names_round_trip() {
        for mode in [Compat::Corrected, Compat::Upstream] {
            assert_eq!(mode.name().parse::<Compat>().unwrap(), mode);
        }
        assert!("bug-compat".parse::<Compat>().is_err());
    }
}
